### ISSUE TITLE
Tillgång till GitHub student

### ISSUE THREAD

**Issue by scriptcoded** [dbwebb-se/htmlphp#20]
Tjenare!

GitHub student innehåller massor med bra verktyg för studenter, och för att få tillgång behöver man en giltig skol-epost. Tyvärr verkar inte BTHs e-post uppfylla kraven för att GitHub automatiskt ska kunna verifiera en. Därför behöver man skicka in en bild på ett giltigt dokument som bevisar att man går på skolan. Detta kan inte vara en PDF. Finns det något smidigt sätt att få tag på något sådant, eller är det bäst att bara beställa ett BTH-kort?

Här är en länk till GitHub där de förklarar vilken typ av bevis som behövs: https://github.blog/2019-07-30-how-to-get-the-github-student-developer-pack-without-a-student-id/#what-proof-do-i-need-to-submit-for-academic-verification

Tack på förhand!
Malcolm Nihlén

PS.
Vet inte om detta blev rätt repo nu, men håller tummarna :)

**Comment by mosbth** [comment]
Jag frågar IT-helpdesk om råd.

Men läser jag texten från GitHub så säger de "bild" och "you may upload a current transcript". Jag hade plockat ut ett utdrag från ladok (pdf) och tagit en skärmdump på det. Eventuellt hade jag ringat in mitt namn, epostadress och datum för utdraget, så att de tydligt ser att det är "jag" och det är "jag som är student".

Verkar även som en "a time-stamped screenshot of your school portal", en snapshot från Canvas, eller att man är inloggad på studentportalen, eller tom Ladok, kan vara tillräcklligt för att de kan se dig, din epost och kopplingen till att du är registrerad på skolan ett aktuellt datum.

**Comment by scriptcoded** [comment]
Tack mos,

> Verkar även som en "a time-stamped screenshot of your school portal", en snapshot från Canvas

Förstår inte hur jag kan ha missat detta. Ska testa och se om de nöjer sig med det. Isåfall är det ju toppen. Om det inte skulle gå, är det kanske smidigare för dig om jag kontaktar helpdesken själv? :)

**Comment by scriptcoded** [comment]
Uppdatering: Löste det genom att ladda ner ett utdrag från antagning.se på vilket jag sedan tog en skärmdump, ringade in namn, datum, program, skola och texten "Antagen" och skrev även engelska översättningar på allt. Gör någon annan detta så glöm inte att dölja personnummer.
