### ISSUE TITLE
Docker Apache default config

### ISSUE THREAD

**Issue by scriptcoded** [dbwebb-se/htmlphp#21]
`example/docker/site_default.conf` defines `${pathSite}/.log/apache` as its log path. Since `.log` is listed in `.gitignore` this directory doesn't exist on a fresh install and `docker-compose up apache` errors with `Cannot access directory '/app/.log/apache/'`.

Creating `.log/apache` solves this issue.

A `.gitignore` inside both `.log` and `.log/apache` could resolve this. Alternatively just mentioning it to the README might do it.

https://github.com/dbwebb-se/htmlphp/blob/41853939be8fc3c772e80d98d6e3bf370c224fae/example/docker/site_default.conf#L28-L29

**Comment by mosbth** [comment]
Yep. I really thought I did that yesterday... but `.log` was in the `.gitignore` file so I missed it.
Should be corrected now.
